"""empty message

Revision ID: 4c5b4b1f8a23
Revises: 
Create Date: 2022-04-28 12:02:21.462046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5b4b1f8a23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('location_x', sa.Integer(), nullable=True),
    sa.Column('location_y', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('sid', sa.String(length=30), nullable=True),
    sa.Column('axis', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('NORMAL', 'CHARGING', name='jobtype'), nullable=True),
    sa.Column('destination_x', sa.Integer(), nullable=True),
    sa.Column('destination_y', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement')
    op.drop_table('job')
    op.drop_table('robot')
    # ### end Alembic commands ###
