"""empty message

Revision ID: 785989d7fa5d
Revises: 
Create Date: 2022-04-22 11:25:56.153058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785989d7fa5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_x', sa.Integer(), nullable=True),
    sa.Column('location_y', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_x', sa.Integer(), nullable=True),
    sa.Column('destination_y', sa.Integer(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement')
    op.drop_table('job')
    op.drop_table('robot')
    # ### end Alembic commands ###
