"""empty message

Revision ID: e898f7f03220
Revises: 785989d7fa5d
Create Date: 2022-04-22 11:50:51.466646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e898f7f03220'
down_revision = '785989d7fa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'status')
    # ### end Alembic commands ###
